charset: UTF-8

serializer: JSON

engines:
  JSON:
    pretty: 0


plugins:
      DBIC:
        default:
          dsn: dbi:Pg:dbname=chado_webtest_01
          schema_class: Bio::Chado::VBPopBio

      MemcachedFast:
        servers:
          - "127.0.0.1:11211"
        default_timeout: 0
        namespace: "popbio:"
        compress_threshold: 10000

logger: 'file'
log: 'debug'


