serializer: JSON

plugins:
      DBIC:
        default:
          dsn: dbi:Pg:dbname=chado_webtest_01
          schema_class: Bio::Chado::VBPopBio

      MemcachedFast:
        servers:
          - "127.0.0.1:11211"
        default_timeout: 0
        namespace: "popbio:"

logger: 'file'
log: 'debug'


